spring.application.name=proyectopruebas

# Puerto local
server.port=8112
spring.data.mongodb.database=saberprodb
# Configuración de MongoDB
spring.data.mongodb.uri=mongodb+srv://esangemari1_db_user:12345@cluster0.emhunz5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

# (Opcional) Desactivar logs excesivos
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
